const { getDb } = require('../firebase');

const STAMPS_REQUIRED = parseInt(process.env.STAMPS_REQUIRED) || 6;

/**
 * POST /barista/scan
 * body: { qrData: string, stamps: number, shopId: string, shopSecret: string }
 *
 * qrData shape: { userId, ts }  — generated by the user's app
 * shopSecret — the shop's secret (barista knows it)
 */
async function handleBaristaScan(req, res, next) {
  try {
    const { qrData, stamps, shopId, shopSecret } = req.body;

    // ── 1. Validate input ────────────────────────────────────────────────────
    if (!qrData || !stamps || !shopId || !shopSecret) {
      return res.status(400).json({ error: 'Missing required fields.' });
    }

    const stampsNum = parseInt(stamps);
    if (isNaN(stampsNum) || stampsNum < 1 || stampsNum > 10) {
      return res.status(400).json({ error: 'stamps must be between 1 and 10.' });
    }

    // ── 2. Parse user QR ─────────────────────────────────────────────────────
    let parsed;
    try {
      parsed = typeof qrData === 'string' ? JSON.parse(qrData) : qrData;
    } catch {
      return res.status(400).json({ error: 'Invalid QR code format.' });
    }

    const { userId, ts } = parsed;
    if (!userId) {
      return res.status(400).json({ error: 'QR code missing userId.' });
    }

    // ── 3. QR freshness check (10 minutes) ───────────────────────────────────
    if (ts) {
      const age = Date.now() - Number(ts);
      const maxAge = 10 * 60 * 1000;
      if (age > maxAge || age < 0) {
        return res.status(400).json({ error: 'QR code has expired. Ask the customer to refresh it.' });
      }
    }

    // ── 4. Validate shop & secret ────────────────────────────────────────────
    const db = getDb();
    const shopSnap = await db.collection('shops').doc(shopId).get();
    if (!shopSnap.exists) {
      return res.status(404).json({ error: 'Shop not found.' });
    }

    const shop = shopSnap.data();
    if (shop.secret !== shopSecret) {
      return res.status(403).json({ error: 'Invalid shop secret.' });
    }

    // ── 5. Load / create user ────────────────────────────────────────────────
    const userRef = db.collection('users').doc(String(userId));
    const userSnap = await userRef.get();
    const now = Date.now();

    let userData = userSnap.exists
      ? userSnap.data()
      : { coffees: {}, rewards: 0, lastScanAt: {}, createdAt: now };

    // ── 6. Add stamps, handle free coffees ───────────────────────────────────
    const currentStamps = (userData.coffees?.[shopId] || 0) + stampsNum;
    let rewards = userData.rewards || 0;
    let freeEarned = 0;
    let finalStamps = currentStamps;

    // Handle multiple free coffees if stamps overflow
    while (finalStamps >= STAMPS_REQUIRED) {
      finalStamps -= STAMPS_REQUIRED;
      freeEarned += 1;
      rewards += 1;
    }

    const update = {
      [`coffees.${shopId}`]: finalStamps,
      rewards,
      [`lastScanAt.${shopId}`]: now,
    };

    if (userSnap.exists) {
      await userRef.update(update);
    } else {
      await userRef.set({ coffees: { [shopId]: finalStamps }, rewards, lastScanAt: { [shopId]: now }, createdAt: now });
    }

    let message;
    if (freeEarned > 0) {
      message = `🎉 ${freeEarned} free coffee${freeEarned > 1 ? 's' : ''} earned! ${finalStamps} stamp${finalStamps !== 1 ? 's' : ''} remaining.`;
    } else {
      const remaining = STAMPS_REQUIRED - finalStamps;
      message = `☕ +${stampsNum} stamp${stampsNum !== 1 ? 's' : ''} added! ${remaining} more for a free coffee.`;
    }

    return res.json({
      success: true,
      message,
      coffees: finalStamps,
      rewards,
      shopId,
      freeEarned: freeEarned > 0,
      freeCount: freeEarned,
      userId,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * POST /barista/verify
 * body: { shopId, shopSecret }
 * Returns shop info if secret is valid — used for barista login
 */
async function verifyBarista(req, res, next) {
  try {
    const { shopId, shopSecret } = req.body;
    if (!shopId || !shopSecret) {
      return res.status(400).json({ error: 'shopId and shopSecret required.' });
    }

    const db = getDb();
    const shopSnap = await db.collection('shops').doc(shopId).get();
    if (!shopSnap.exists) {
      return res.status(404).json({ error: 'Shop not found.' });
    }

    const shop = shopSnap.data();
    if (shop.secret !== shopSecret) {
      return res.status(403).json({ error: 'Wrong password.' });
    }

    return res.json({ success: true, shop: { id: shopId, name: shop.name, emoji: shop.emoji || '☕' } });
  } catch (err) {
    next(err);
  }
}

module.exports = { handleBaristaScan, verifyBarista };
